const coinOptions = [
    { value: "BTC", name: "Bitcoin (BTC)" },
    { value: "ETH", name: "Ethereum (ETH)" },
    { value: "USDT", name: "Tether (USDT)" },
    { value: "BNB", name: "Binance Coin (BNB)" },
    { value: "USDC", name: "USD Coin (USDC)" },
    { value: "XRP", name: "Ripple (XRP)" },
    { value: "ADA", name: "Cardano (ADA)" },
    { value: "DOGE", name: "Dogecoin (DOGE)" },
    { value: "MATIC", name: "Polygon (MATIC)" },
    { value: "SOL", name: "Solana (SOL)" },
    { value: "DOT", name: "Polkadot (DOT)" },
    { value: "BUSD", name: "Binance USD (BUSD)" },
    { value: "LTC", name: "Litecoin (LTC)" },
    { value: "SHIB", name: "Shiba Inu (SHIB)" },
    { value: "TRX", name: "TRON (TRX)" },
    { value: "AVAX", name: "Avalanche (AVAX)" },
    { value: "DAI", name: "Dai (DAI)" },
    { value: "UNI", name: "Uniswap (UNI)" },
    { value: "WBTC", name: "Wrapped Bitcoin (WBTC)" },
    { value: "LINK", name: "Chainlink (LINK)" },
    { value: "ATOM", name: "Cosmos (ATOM)" },
    { value: "LEO", name: "UNUS SED LEO (LEO)" },
    { value: "ETC", name: "Ethereum Classic (ETC)" },
    { value: "XMR", name: "Monero (XMR)" },
    { value: "OKB", name: "OKB (OKB)" },
    { value: "XLM", name: "Stellar (XLM)" },
    { value: "BCH", name: "Bitcoin Cash (BCH)" },
    { value: "FIL", name: "Filecoin (FIL)" },
    { value: "LDO", name: "Lido DAO (LDO)" },
    { value: "CRO", name: "Cronos (CRO)" },
    { value: "NEAR", name: "NEAR Protocol (NEAR)" },
    { value: "VET", name: "VeChain (VET)" },
    { value: "ICP", name: "Internet Computer (ICP)" },
    { value: "GRT", name: "The Graph (GRT)" },
    { value: "FLOW", name: "Flow (FLOW)" },
    { value: "HBAR", name: "Hedera (HBAR)" },
    { value: "AAVE", name: "Aave (AAVE)" },
    { value: "QNT", name: "Quant (QNT)" },
    { value: "EGLD", name: "MultiversX (EGLD)" },
    { value: "THETA", name: "Theta Network (THETA)" },
    { value: "EOS", name: "EOS (EOS)" },
    { value: "SAND", name: "The Sandbox (SAND)" },
    { value: "MANA", name: "Decentraland (MANA)" },
    { value: "AXS", name: "Axie Infinity (AXS)" },
    { value: "XTZ", name: "Tezos (XTZ)" },
    { value: "TUSD", name: "TrueUSD (TUSD)" },
    { value: "APE", name: "ApeCoin (APE)" },
    { value: "BSV", name: "Bitcoin SV (BSV)" },
    { value: "CHZ", name: "Chiliz (CHZ)" },
    { value: "ALGO", name: "Algorand (ALGO)" },
    { value: "KCS", name: "KuCoin Token (KCS)" },
    { value: "FTM", name: "Fantom (FTM)" },
    { value: "USDP", name: "Pax Dollar (USDP)" },
    { value: "KLAY", name: "Klaytn (KLAY)" },
    { value: "HT", name: "Huobi Token (HT)" },
    { value: "NEO", name: "NEO (NEO)" },
    { value: "MIOTA", name: "IOTA (MIOTA)" },
    { value: "BTCB", name: "Bitcoin BEP2 (BTCB)" },
    { value: "CRV", name: "Curve DAO Token (CRV)" },
    { value: "USDD", name: "USDD (USDD)" },
    { value: "STX", name: "Stacks (STX)" },
    { value: "CAKE", name: "PancakeSwap (CAKE)" },
    { value: "RUNE", name: "THORChain (RUNE)" },
    { value: "ZEC", name: "Zcash (ZEC)" },
    { value: "XEC", name: "eCash (XEC)" },
    { value: "WAVES", name: "Waves (WAVES)" },
    { value: "MKR", name: "Maker (MKR)" },
    { value: "ENJ", name: "Enjin Coin (ENJ)" },
    { value: "DASH", name: "Dash (DASH)" },
    { value: "PAXG", name: "PAX Gold (PAXG)" },
    { value: "NEXO", name: "Nexo (NEXO)" },
    { value: "BAT", name: "Basic Attention Token (BAT)" },
    { value: "CELO", name: "Celo (CELO)" },
    { value: "GMT", name: "STEPN (GMT)" },
    { value: "KAVA", name: "Kava (KAVA)" },
    { value: "ROSE", name: "Oasis Network (ROSE)" },
    { value: "ZIL", name: "Zilliqa (ZIL)" },
    { value: "MINA", name: "Mina (MINA)" },
    { value: "1INCH", name: "1inch Network (1INCH)" },
    { value: "COMP", name: "Compound (COMP)" },
    { value: "XDC", name: "XDC Network (XDC)" },
    { value: "HOT", name: "Holo (HOT)" },
    { value: "AR", name: "Arweave (AR)" },
    { value: "GALA", name: "Gala (GALA)" },
    { value: "DCR", name: "Decred (DCR)" },
    { value: "KSM", name: "Kusama (KSM)" },
    { value: "LRC", name: "Loopring (LRC)" },
    { value: "QTUM", name: "Qtum (QTUM)" },
    { value: "GT", name: "GateToken (GT)" },
    { value: "FEI", name: "Fei USD (FEI)" },
    { value: "SNX", name: "Synthetix (SNX)" },
    { value: "ANKR", name: "Ankr (ANKR)" },
    { value: "RVN", name: "Ravencoin (RVN)" },
    { value: "IOST", name: "IOST (IOST)" },
    { value: "TFUEL", name: "Theta Fuel (TFUEL)" },
    { value: "OP", name: "Optimism (OP)" },
    { value: "YFI", name: "yearn.finance (YFI)" },
    { value: "WAXP", name: "WAX (WAXP)" },
    { value: "BORA", name: "BORA (BORA)" },
    { value: "CSPR", name: "Casper (CSPR)" },
    { value: "GLMR", name: "Moonbeam (GLMR)" },
    { value: "AUDIO", name: "Audius (AUDIO)" },
    { value: "CHSB", name: "SwissBorg (CHSB)" },
    { value: "LUNA", name: "Terra (LUNA)" },
    { value: "DYDX", name: "dYdX (DYDX)" },
    { value: "POLY", name: "Polymath (POLY)" },
    { value: "IOTX", name: "IoTeX (IOTX)" },
    { value: "ONE", name: "Harmony (ONE)" },
    { value: "OMG", name: "OMG Network (OMG)" },
    { value: "CELR", name: "Celer Network (CELR)" },
    { value: "ICX", name: "ICON (ICX)" },
    { value: "HIVE", name: "Hive (HIVE)" },
    { value: "SXP", name: "Swipe (SXP)" },
    { value: "OCEAN", name: "Ocean Protocol (OCEAN)" },
    { value: "STORJ", name: "Storj (STORJ)" },
    { value: "CKB", name: "Nervos Network (CKB)" },
    { value: "SUSHI", name: "SushiSwap (SUSHI)" },
    { value: "XYM", name: "Symbol (XYM)" },
    { value: "KEEP", name: "Keep Network (KEEP)" },
    { value: "SKL", name: "SKALE Network (SKL)" },
    { value: "BAKE", name: "BakeryToken (BAKE)" },
    { value: "STEEM", name: "Steem (STEEM)" },
    { value: "CTSI", name: "Cartesi (CTSI)" },
    { value: "NANO", name: "Nano (NANO)" },
    { value: "ALPHA", name: "Alpha Finance Lab (ALPHA)" },
    { value: "REEF", name: "Reef (REEF)" },
    { value: "BAND", name: "Band Protocol (BAND)" },
    { value: "REN", name: "Ren (REN)" },
    { value: "FET", name: "Fetch.ai (FET)" },
    { value: "COTI", name: "COTI (COTI)" },
    { value: "STMX", name: "StormX (STMX)" },
    { value: "OGN", name: "Origin Protocol (OGN)" },
    { value: "STRAX", name: "Stratis (STRAX)" },
    { value: "DENT", name: "Dent (DENT)" },
    { value: "VTHO", name: "VeThor Token (VTHO)" },
    { value: "WRX", name: "WazirX (WRX)" },
    { value: "RSR", name: "Reserve Rights (RSR)" },
    { value: "MAID", name: "MaidSafeCoin (MAID)" },
    { value: "ARDR", name: "Ardor (ARDR)" },
    { value: "NMR", name: "Numeraire (NMR)" },
    { value: "WIN", name: "WINkLink (WIN)" },
    { value: "ORBS", name: "Orbs (ORBS)" },
    { value: "POWR", name: "Power Ledger (POWR)" },
    { value: "KMD", name: "Komodo (KMD)" },
    { value: "XVG", name: "Verge (XVG)" },
    { value: "PROM", name: "Prometeus (PROM)" },
    { value: "INJ", name: "Injective (INJ)" },
    { value: "TOMO", name: "TomoChain (TOMO)" },
    { value: "BZRX", name: "bZx Protocol (BZRX)" },
    { value: "FORTH", name: "Ampleforth Governance Token (FORTH)" },
    { value: "WOZX", name: "Efforce (WOZX)" },
    { value: "DODO", name: "DODO (DODO)" },
    { value: "VITE", name: "VITE (VITE)" },
    { value: "YFII", name: "DFI.Money (YFII)" },
    { value: "HARD", name: "Kava Lend (HARD)" },
    { value: "ANT", name: "Aragon (ANT)" },
    { value: "NULS", name: "NULS (NULS)" },
    { value: "AKRO", name: "Akropolis (AKRO)" },
    { value: "DOCK", name: "Dock (DOCK)" },
    { value: "RAMP", name: "RAMP (RAMP)" },
    { value: "PERL", name: "PERL.eco (PERL)" },
    { value: "LOOM", name: "Loom Network (LOOM)" },
    { value: "WNXM", name: "Wrapped NXM (WNXM)" },
    { value: "OXT", name: "Orchid (OXT)" },
    { value: "MBOX", name: "MOBOX (MBOX)" },
    { value: "CTXC", name: "Cortex (CTXC)" },
    { value: "TRB", name: "Tellor (TRB)" },
    { value: "BTS", name: "BitShares (BTS)" },
    { value: "BADGER", name: "Badger DAO (BADGER)" },
    { value: "FIO", name: "FIO Protocol (FIO)" },
    { value: "WING", name: "Wing Finance (WING)" },
    { value: "AION", name: "Aion (AION)" },
    { value: "POND", name: "Marlin (POND)" },
    { value: "RNDR", name: "Render Token (RNDR)" },
    { value: "POLS", name: "Polkastarter (POLS)" },
    { value: "SCRT", name: "Secret (SCRT)" },
    { value: "IDEX", name: "IDEX (IDEX)" },
    { value: "KNCL", name: "Kyber Network Crystal Legacy (KNCL)" },
    { value: "TRAC", name: "OriginTrail (TRAC)" },
    { value: "DUSK", name: "Dusk Network (DUSK)" },
    { value: "UNFI", name: "Unifi Protocol DAO (UNFI)" },
    { value: "FRONT", name: "Frontier (FRONT)" },
    { value: "BURGER", name: "BurgerCities (BURGER)" },
    { value: "ARPA", name: "ARPA Chain (ARPA)" },
    { value: "AUTO", name: "Auto (AUTO)" },
    { value: "GHST", name: "Aavegotchi (GHST)" },
    { value: "JASMY", name: "JasmyCoin (JASMY)" },
    { value: "1000SATS", name: "1000SATS" },
    { value: "PEPE", name: "Pepe (PEPE)" }
]