version: '3'

services:
  backend:
    build: ./bina-backend
    environment:
      - BINANCE_TESTNET_API_KEY
      - BINANCE_TESTNET_SECRET_KEY
      - BINANCE_API_KEY
      - BINANCE_SECRET_KEY
    network_mode: host
    volumes:
      - ./bina-backend:/app
    working_dir: /app

  frontend:
    build: ./bina-frontend-simple
    network_mode: host
    depends_on:
      - backend
    volumes:
      - ./bina-frontend-simple:/app
    working_dir: /app

# The networks section is removed as it's not needed with host network mode